#!/system/xbin/sh

# remount rootfs rw
mount -o remount,rw rootfs /

cp /system/xbin/sh /sbin/sh
chmod 755 /sbin/sh

cp /system/bin/recovery.sh /sbin/recovery.sh
chmod 755 /sbin/recovery.sh

/sbin/recovery.sh

exit 0
