#!/system/xbin/busybox sh

BUSYBOX=/system/xbin/busybox

# remount rootfs rw
${BUSYBOX} mount -o remount,rw rootfs /

${BUSYBOX} cp /system/xbin/busybox /sbin/busybox
${BUSYBOX} chmod 755 /sbin/busybox

${BUSYBOX} cp /system/bin/recovery.sh /sbin/recovery.sh
${BUSYBOX} chmod 755 /sbin/recovery.sh

exec /sbin/recovery.sh
